services:
  postgres:
    image: postgres:16-alpine
    container_name: star_rail_database
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DB}
    ports:
      - "${POSTGRESQL_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRESQL_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    init: true
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - redis
    command: npm run dev -- --host 0.0.0.0
    env_file:
      - ./frontend/.env

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    env_file:
      - ./backend/.env

  worker:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: node redis/worker/loginWorker.js
    depends_on:
      - redis
    env_file:
      - ./backend/.env

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    
volumes:
  postgres_data:
