services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - redis
    command: npm run dev -- --host 0.0.0.0
    env_file:
      - ./frontend/.env

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres
    env_file:
      - ./backend/.env

  worker:
    build: ./backend
    command: node redis/worker/loginWorker.js
    depends_on:
      - redis
    env_file:
      - ./backend/.env

  redis:
    image: redis:7

  postgres:
    image: postgres:16-alpine
    container_name: star_rail_database
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DB}
    ports:
      - "${POSTGRESQL_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data: