export const Stts = {
  HPDelta: {
    name: "PV",
    field: "hp",
    percent: false,
    affix: true,
    main: ["head"],
    Summary: "Vida",
    maxValue: 705,
    icon: "icon/property/IconMaxHP.png",
  },

  HPAddedRatio: {
    name: "PV%",
    field: "hp",
    percent: true,
    affix: true,
    main: ["body", "boots", "sphere", "rope"],
    Summary: undefined,
    maxValue: 43.2,
    icon: "icon/property/IconMaxHP.png",
  },

  AttackDelta: {
    name: "ATQ",
    field: "atk",
    percent: false,
    affix: true,
    main: ["hands"],
    Summary: "Ataque",
    maxValue: 352,
    icon: "icon/property/IconAttack.png",
  },

  AttackAddedRatio: {
    name: "ATQ%",
    field: "atk",
    percent: true,
    affix: true,
    main: ["body", "boots", "sphere", "rope"],
    Summary: undefined,
    maxValue: 43.2,
    icon: "icon/property/IconAttack.png",
  },

  DefenceDelta: {
    name: "DEF",
    field: "def",
    percent: false,
    affix: true,
    main: [],
    Summary: "Defesa",
    icon: "icon/property/IconDefence.png",
  },

  DefenceAddedRatio: {
    name: "DEF%",
    field: "def",
    percent: true,
    affix: true,
    main: ["body", "boots", "sphere", "rope"],
    Summary: undefined,
    maxValue: 54.0,
    icon: "icon/property/IconDefence.png",
  },

  SpeedDelta: {
    name: "Velocidade",
    field: "spd",
    percent: false,
    affix: true,
    main: ["boots"],
    Summary: "Velocidade",
    maxValue: 25,
    icon: "icon/property/IconSpeed.png",
  },

  CriticalChanceBase: {
    name: "Taxa Crit",
    field: "crit_rate",
    percent: true,
    affix: true,
    main: ["body"],
    Summary: "Taxa Critica",
    maxValue: 32.4,
    icon: "icon/property/IconCriticalChance.png",
  },

  CriticalDamageBase: {
    name: "Dano Crit",
    field: "crit_dmg",
    percent: true,
    affix: true,
    main: ["body"],
    Summary: "Dano Critico",
    maxValue: 64.8,
    icon: "icon/property/IconCriticalDamage.png",
  },

  BreakDamageAddedRatioBase: {
    name: "Break Effect",
    field: "break",
    percent: true,
    affix: true,
    main: ["rope"],
    Summary: "Efeito de Quebra",
    maxValue: 64.8,
    icon: "icon/property/IconBreakUp.png",
  },

  StatusProbabilityBase: {
    name: "Effect Hit Rate",
    field: "effect_hit",
    percent: true,
    affix: true,
    main: ["body"],
    Summary: "Taxa de Acerto de Efeito",
    maxValue: 43.2,
    icon: "icon/property/IconStatusProbability.png",
  },

  StatusResistanceBase: {
    name: "Effect RES",
    field: "effect_res",
    percent: true,
    affix: true,
    main: ["body"],
    Summary: "Resistencia a Efeito",
    icon: "icon/property/IconStatusResistance.png",
  },

  HealRatioBase: {
    name: "Cura",
    field: "heal",
    percent: true,
    affix: false,
    main: ["body"],
    Summary: "Bônus de Cura",
    maxValue: 34.5,
    icon: "icon/property/IconHealRatio.png",
  },

  SPDRatio: {
    name: "Energy Regen",
    field: "energy",
    percent: true,
    affix: false,
    main: ["rope"],
    Summary: "Regeneração de Energia",
    maxValue: 19.4,
    icon: "icon/property/IconEnergyRecovery.png",
  },

  PhysicalAddedRatio: {
    name: "Dano Físico",
    field: "dmg",
    element: "physical",
    percent: true,
    affix: false,
    main: ["sphere"],
    Summary: "Dano Físico",
    maxValue: 38.8,
    icon: "icon/property/IconPhysicalAddedRatio.png",
  },

  FireAddedRatio: {
    name: "Dano Fogo",
    field: "dmg",
    element: "fire",
    percent: true,
    affix: false,
    main: ["sphere"],
    Summary: "Dano Fogo",
    maxValue: 38.8,
    icon: "icon/property/IconFireAddedRatio.png",
  },

  IceAddedRatio: {
    name: "Dano Gelo",
    field: "dmg",
    element: "ice",
    percent: true,
    affix: false,
    main: ["sphere"],
    Summary: "Dano Gelo",
    maxValue: 38.8,
    icon: "icon/property/IconIceAddedRatio.png",
  },

  ThunderAddedRatio: {
    name: "Dano Raio",
    field: "dmg",
    element: "lightning",
    percent: true,
    affix: false,
    main: ["sphere"],
    Summary: "Dano Raio",
    maxValue: 38.8,
    icon: "icon/property/IconThunderAddedRatio.png",
  },

  WindAddedRatio: {
    name: "Dano Vento",
    field: "dmg",
    element: "wind",
    percent: true,
    affix: false,
    main: ["sphere"],
    Summary: "Dano Vento",
    maxValue: 38.8,
    icon: "icon/property/IconWindAddedRatio.png",
  },

  QuantumAddedRatio: {
    name: "Dano Quantum",
    field: "dmg",
    element: "quantum",
    percent: true,
    affix: false,
    main: ["sphere"],
    Summary: "Dano Quantum",
    maxValue: 38.8,
    icon: "icon/property/IconQuantumAddedRatio.png",
  },

  ImaginaryAddedRatio: {
    name: "Dano Imaginário",
    field: "dmg",
    element: "imaginary",
    percent: true,
    affix: false,
    main: ["sphere"],
    Summary: "Dano Imaginário",
    maxValue: 38.8,
    icon: "icon/property/IconImaginaryAddedRatio.png",
  },
};
